### PR TITLE
Fix app crash trying to show the search results page

### LINKED ISSUE #1438: The app crashes trying to show the search results page
### Which version of the app?

WinUI 3 Gallery

### Description

To reproduce the crash, enter some text like "button" in the search box and press Enter.

### Screenshots

_No response_

### Windows version

_No response_

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by AndrewKeepCoding**
## Description
Set the placeholder image "Placeholder.png" in case that ControlInfoDataPath item's ImagePath is null.

## Motivation and Context
Fixes #1438.

## How Has This Been Tested?
Tested on the updated app.

## Types of changes
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

### CODE REVIEW

**Comment by karkarl** [comment]
Thanks so much for the fix! We should definitely add a test to avoid future regressions, do you mind appending that to this PR?

**Comment by AndrewKeepCoding** [comment]
> Thanks so much for the fix! We should definitely add a test to avoid future regressions, do you mind appending that to this PR?

Good point!
But I'm having issues trying to run the UI Tests. I followed the [instructions](https://github.com/microsoft/WinUI-Gallery/tree/main/UITests#ui-tests-with-winappdriver) but I'm getting the exceptions below:

image

I need to find time to take a look at this error. Any tips?

**Comment by marcelwgn** [comment]
Hi @AndrewKeepCoding thank you for creating this PR! Can you try running the WinUI Gallery Packaged workload from Visual Studio and then see if the testsw are able to pick up the application?

If that does not help, can you try running the following command `Get-AppxPackage` and show the packages that have `WinUI3ControlsGallery` in the name?

**Comment by AndrewKeepCoding** [comment]
@marcelwgn Thanks for the tips. It worked but not sure if it was the WinAppDriver version (v1.2.99 -> v1.2.1) or the "alternatives" on the instructions...🙃

@karkarl I added an UI test that shows the results page and click each group result menu item. Let me know if can improve it since this is my first time writing a test with WinAppDriver.🙃

File: UITests/Tests/SearchResults.cs [hunk 1]
```diff
@@ -0,0 +1,53 @@
...
+    [TestClass]
+    public class SearchResults : TestBase
+    {
+        [ClassInitialize]
+        public static void ClassInitialize(TestContext context)
+        {
+        }
+
+        [TestMethod]
+        [DataRow("a")]  // "a" should return results for all groups.
```
Comment (karkarl) [inline UITests/Tests/SearchResults.cs:32]: nit: add description like so
`[TestProperty("Description", "Scan through all search results page for accessibility issues.")]`

File: UITests/Tests/SearchResults.cs [hunk 2]
```diff
@@ -0,0 +1,53 @@
...
+
+            Thread.Sleep(100);
+
+            var resultsNavView = Session.FindElementByAccessibilityId("resultsNavView");
+            var resultItems = resultsNavView.FindElements(By.ClassName("Microsoft.UI.Xaml.Controls.NavigationViewItem"));
+
+            foreach (var menuItem in resultItems)
+            {
+                Thread.Sleep(1000);
+                menuItem.Click();
```
Comment (karkarl) [inline UITests/Tests/SearchResults.cs:49]: We might as well add an axe scan assert here since we're going through all the pages anyways with -
`AxeHelper.AssertNoAccessibilityErrors();`

**Comment by karkarl** [comment]
> @karkarl I added an UI test that shows the results page and click each group result menu item. Let me know if can improve it since this is my first time writing a test with WinAppDriver.🙃

Thanks so much for your help! I've added some suggestions to your PR, can't wait to get this in!

**Comment by AndrewKeepCoding** [comment]
@karkarl  Thanks for the tips. Updated the test.

**Review by karkarl — APPROVED** [review]
